# Generated by Django 4.1.4 on 2022-12-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='The Genre Name In Sentense Case', max_length=50)),
                ('Banner', models.ImageField(default='none', upload_to='Genres')),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Movies.movie')),
            ],
        ),
    ]
