# Generated by Django 4.1.4 on 2022-12-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='MovieId',
        ),
    ]
