# Generated by Django 4.1.4 on 2022-12-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieId', models.CharField(help_text='Movie Id from IMDB', max_length=20)),
                ('Title', models.CharField(max_length=200)),
                ('YoR', models.CharField(help_text='Year of Release', max_length=4)),
                ('CoR', models.CharField(help_text='Content Rating', max_length=20)),
                ('MovieLength', models.CharField(help_text='The Length of the movie in Minutes', max_length=4)),
                ('StarRatings', models.IntegerField(default=0)),
                ('Genres', models.CharField(max_length=20)),
                ('MovieKeywords', models.CharField(max_length=20)),
                ('Banner', models.CharField(help_text='Movie Banner to display', max_length=200)),
                ('RandomId', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
