# Generated by Django 4.1.4 on 2022-12-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='RandomId',
            field=models.CharField(default='ktP02JO7', max_length=20),
        ),
    ]
