# Generated by Django 4.1.4 on 2022-12-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_movie_randomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='MovieKeywords',
        ),
        migrations.AlterField(
            model_name='movie',
            name='RandomId',
            field=models.CharField(max_length=20),
        ),
    ]
