# Generated by Django 4.1.4 on 2022-12-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0002_remove_genre_movieid'),
        ('Keywords', '0001_initial'),
        ('Movies', '0003_remove_movie_genres_remove_movie_moviekeywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Genres',
            field=models.ManyToManyField(to='Genres.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='MovieKeywords',
            field=models.ManyToManyField(to='Keywords.keyword'),
        ),
    ]
