# Generated by Django 4.1.4 on 2022-12-30 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_movie_genres_movie_moviekeywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['YoR'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='Status',
            field=models.CharField(choices=[('latest', 'Latest'), ('upcoming', 'Upcoming'), ('featured', 'Featured'), ('top', 'Top'), ('suggested', 'Suggested'), ('trending', 'Trending'), ('recommended', 'Recommended'), ('popular', 'Popular'), ('special', 'Special')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
