# Generated by Django 4.1.4 on 2022-12-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0002_remove_genre_movieid'),
        ('Movies', '0005_alter_movie_options_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Genres',
            field=models.ManyToManyField(related_name='genres', to='Genres.genre'),
        ),
    ]
