# Generated by Django 4.1.4 on 2022-12-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Description',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Plot',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Slug',
            field=models.SlugField(default='None'),
            preserve_default=False,
        ),
    ]
