# Generated by Django 4.1.4 on 2022-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_movie_description_movie_plot_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Status',
            field=models.CharField(choices=[('latest', 'Latest'), ('upcoming', 'Upcoming'), ('featured', 'Featured'), ('top', 'Top'), ('suggested', 'Suggested'), ('trending', 'Trending'), ('recommended', 'Recommended'), ('popular', 'Popular'), ('special', 'Special')], default='recommended', max_length=50),
        ),
    ]
