# Generated by Django 4.1.4 on 2022-12-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_alter_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Image',
            field=models.CharField(default=models.CharField(help_text='Movie Banner to display', max_length=200), help_text='Image to Display to Frontends', max_length=200),
        ),
    ]
