# Generated by Django 4.1.4 on 2022-12-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0008_alter_movie_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ActorId', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('ActorMovie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='Movies.movie')),
            ],
        ),
    ]
